# -*- coding: utf-8 -*-
"""nms hackathon team SPS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tL36tbTRU_N0kJ-fBXCDNx2ceNu3LvUt
"""

# Commented out IPython magic to ensure Python compatibility.
# #SPS HACKATHON TEAM  GRADE 8 (NMS)
# %%html
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Medical Form</title>
#     <style>
#         body {
#             font-family: Arial, sans-serif;
#             background-color: #f2f2f2; /* Set background color to light gray */
#             margin: 0;
#             padding: 0;
#         }
# 
#         .container {
#             max-width: 600px;
#             margin: 50px auto;
#             padding: 20px;
#             background-color: #fff;
#             border-radius: 8px;
#             box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
#         }
# 
#         h2 {
#             text-align: center;
#             color: #333;
#         }
# 
#         form {
#             margin-top: 20px;
#         }
# 
#         label {
#             font-weight: bold;
#             color: black
#         }
# 
#         input[type="text"],
#         input[type="email"],
#         select {
#             width: 100%;
#             padding: 10px;
#             margin: 5px 0 15px;
#             border: 1px solid #ccc;
#             border-radius: 4px;
#             box-sizing: border-box;
#         }
# 
#         button[type="submit"] {
#             background-color: #4caf50;
#             color: white;
#             padding: 12px 20px;
#             border: none;
#             border-radius: 4px;
#             cursor: pointer;
#             width: 100%;
#             margin-top: 10px;
#         }
# 
#         button[type="submit"]:hover {
#             background-color: #45a049;
#         }
# 
#         #doctorInfo {
#             margin-top: 20px;
#             border-top: 1px solid #ccc;
#             padding-top: 20px;
#             color: black;
#         }
#     </style>
# 
# </head>
# <body>
#     <h2>Medical Form</h2>
#     <form id="medicalForm">
#        <label for="name">Name:</label><br>
#         <input type="text" id="name" name="name" required><br>
# 
#         <label for="Address">Address:</label><br>
#         <input type="text" id="address" name="address" required><br>
# 
#         <label for="Age">Age:</label><br>
#         <input type="text" id="Age" name="age" required><br>
# 
#         <label for="phone">Phone:</label><br>
#         <input type="text" id="phone" name="phone" required><br>
# 
#         <label for="email">Email:</label><br>
#         <input type="email" id="email" name="email" required><br>
# 
#         <label for="medical_issue">Medical Issue:</label><br>
#         <select id="medical_issue" name="medical_issue">
# 
#             <option value="mental_illness">Mental Illness</option>
#             <option value="heart_issue">Heart Issue</option>
#             <option value="lung_issue">Lung Issue</option>
#             <option value="fractured_bones">Fractured Bones</option>
#             <option value="blood_loss">Blood Loss</option>
#             <option value="weakness">Weakness</option>
#             <option value="body_aches">Body Aches</option>
#             <option value="motion_sickness">Motion Sickness</option>
#         </select><br><br>
# 
#         <button type="submit">Submit</button>
#     </form>
# 
#     <div id="doctorInfo"></div>
# 
#     <script>
#         document.getElementById("medicalForm").addEventListener("submit", function(event) {
#             event.preventDefault(); // Prevent the form from submitting
# 
#             // Get form data
#             var formData = new FormData(event.target);
# 
#             // Extract form fields
#             var name = formData.get("name");
#             var email = formData.get("email");
#             var phone = formData.get("phone");
#             var medical_issue = formData.get("medical_issue");
# 
#             // Assign doctor based on medical issue
#             var doctor = "";
#             var contact_number = "";
#             var address = "";
#             var specialization = "";
# 
#             if (["mental_illness", "weakness", "motion_sickness"].includes(medical_issue)) {
#                 doctor = "Pramod Kasliwal";
#                 contact_number = "9000000000";
#                 address = "G6 Mansarovar";
#                 specialization = "Psychiatry";
#             } else if (["heart_issue", "lung_issue", "blood_loss"].includes(medical_issue)) {
#                 doctor = "Ram Kasliwal";
#                 contact_number = "9831112221";
#                 address = "G7 Mansarovar";
#                 specialization = "Lung Diseases";
#             } else if (["fractured_bones", "body_aches"].includes(medical_issue)) {
#                 doctor = "Shyam Kasliwal";
#                 contact_number = "9831122334";
#                 address = "G8 Mansarovar";
#                 specialization = "Orthopedics";
#             }
# 
#             // Display doctor information
#             var doctorInfo = "Assigned Doctor: " + doctor + "<br>";
#             doctorInfo += "Contact Number: " + contact_number + "<br>";
#             doctorInfo += "Address: " + address + "<br>";
#             doctorInfo += "Specialization: " + specialization;
# 
#             document.getElementById("doctorInfo").innerHTML = doctorInfo;
# 
#             // Display thank you message
#             document.body.innerHTML += "<p style='color:black'>We will get back to you soon.</p>";
#         });
#     </script>
# </body>
# </html>
# %%html
# 
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Doctor's Interface</title>
#     <style>
#       head {
#         color: black
#       }
#         body {
#             background-color: white; /* Set background color to white */
#             font-family: Arial, sans-serif; /* Set font family */
#             color: black;
#         }
#     </style>
# </head>
# <body>
#     <h2 style="color: black;">Doctor's Interface</h2>
#     <div id="patientInfo">
#         <!-- Patient information will be displayed here -->
#     </div>
# 
#     <div id="consultation">
#         <h3 style='color:black'>Consultation Schedule</h3>
#         <p>Please provide a time for consultation:</p>
#         <input type="datetime-local" id="consultationTime"><br><br>
#         <button onclick="confirmConsultation()">Confirm Consultation</button>
#     </div>
# 
#     <div id="medicine">
#         <h3 style='color:black'>Prescribed Medicine</h3>
#         <p>Please suggest prescribed medicine for the patient:</p>
#         <textarea id="prescribedMedicine" rows="4" cols="50"></textarea><br><br>
#         <button onclick="suggestMedicine()">Suggest Medicine</button>
#     </div>
# 
#     <script>
#         // Patient information received from previous interface
#         var patientInfo = {
#             name: "ram lal",
#             email: "ram lal@example.com",
#             phone: "1234567890",
#             doctor: "Pramod Kasliwal",
#             medicalIssue: "mental illness"
#         };
# 
#         // Display patient information
#         var patientInfoHtml = "<h3 style='color:black'>Patient Information</h3>";
#         patientInfoHtml += "<p style='color:black'>Name: " + patientInfo.name + "</p>";
#         patientInfoHtml += "<p style='color:black'>Email: " + patientInfo.email + "</p>";
#         patientInfoHtml += "<p style='color:black'>Phone: " + patientInfo.phone + "</p>";
#         patientInfoHtml += "<p style='color:black'>Medical Issue: " + patientInfo.medicalIssue + "</p>";
#         patientInfoHtml += "<p style='color:black'>Assigned Doctor: " + patientInfo.doctor + "</p>";
# 
#         document.getElementById("patientInfo").innerHTML = patientInfoHtml;
# 
#         // Function to confirm consultation time
#         function confirmConsultation() {
#             var consultationTime = document.getElementById("consultationTime").value;
#             if (consultationTime) {
#                 alert("Consultation scheduled for: " + consultationTime);
#             } else {
#                 alert("Please select a consultation time.");
#             }
#         }
# 
#         // Function to suggest prescribed medicine
#         function suggestMedicine() {
#             var prescribedMedicine = document.getElementById("prescribedMedicine").value;
#             if (prescribedMedicine) {
#                 alert("Prescribed medicine suggested: " + prescribedMedicine);
#             } else {
#                 alert("Please provide prescribed medicine for the patient.");
#             }
#         }
#     </script>
# </body>
# </html>
# 
# # HTML code for the form
# form_html = """
# <!DOCTYPE html>
# <html lang="en">
# <head>
#   <meta charset="UTF-8">
#   <meta name="viewport" content="width=device-width, initial-scale=1.0">
#   <title>Detailed Form of Problems</title>
#   <style>
#     body {
#       font-family: Arial, sans-serif;
#       background-color: #f0f0f0;
#     }
# 
#     .container {
#       max-width: 600px;
#       margin: 0 auto;
#       padding: 20px;
#       background-color: #fff;
#       border-radius: 8px;
#       box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
#     }
# 
#     h1 {
#       text-align: center;
#       margin-bottom: 20px;
#       color: black;
#     }
# 
#     label {
#       font-weight: bold;
#       color: black
#     }
# 
#     textarea {
#       width: 100%;
#       margin-bottom: 10px;
#     }
# 
#     input[type="submit"] {
#       background-color: #4CAF50;
#       color: white;
#       padding: 10px 20px;
#       border: none;
#       border-radius: 4px;
#       cursor: pointer;
#       float: right;
#     }
# 
#     input[type="submit"]:hover {
#       background-color: #45a049;
#     }
#   </style>
# </head>
# <body>
#   <div class="container">
#     <h1>Detailed Form of Problems</h1>
#     <form id="problemForm">
#       <label for="problems">Type your problems here:</label><br>
#       <textarea id="problems" name="problems" rows="4" cols="50"></textarea><br>
#       <input type="submit" value="Submit">
#     </form>
#   </div>
# </body>
# </html>
# """
# 
# # Display the HTML form
# display(HTML(form_html))
# from IPython.display import HTML
# 
# # HTML code for the form
# form_html = """
# <!DOCTYPE html>
# <html lang="en">
# <head>
#   <meta charset="UTF-8">
#   <meta name="viewport" content="width=device-width, initial-scale=1.0">
#   <title>Doctor's Prescription</title>
#   <style>
#     body {
#       font-family: Arial, sans-serif;
#       background-color: #f0f0f0;
#     }
# 
#     .container {
#       max-width: 600px;
#       margin: 0 auto;
#       padding: 20px;
#       background-color: #fff;
#       border-radius: 8px;
#       box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
#     }
# 
#     h1 {
#       text-align: center;
#       margin-bottom: 20px;
#       color: black;
#     }
# 
#     label {
#       font-weight: bold;
#       color: black;
#     }
# 
#     textarea {
#       width: 100%;
#       margin-bottom: 10px;
#     }
# 
#     input[type="submit"] {
#       background-color: #4CAF50;
#       color: white;
#       padding: 10px 20px;
#       border: none;
#       border-radius: 4px;
#       cursor: pointer;
#       float: right;
#     }
# 
#     input[type="submit"]:hover {
#       background-color: #45a049;
#     }
#   </style>
# </head>
# <body>
#   <div class="container">
#     <h1>Doctor's Presciption</h1>
#     <form id="solutionForm">
#       <label for="prescription">Type your prescription here:</label><br>
#       <textarea id="prescription" name="prescription" rows="4" cols="50"></textarea><br>
#       <input type="submit" value="Submit">
#     </form>
#   </div>
# </body>
# </html>
# """
# 
# # Display the HTML form
# display(HTML(form_html))
# def generate_html():
#     html_content = """
#     <!DOCTYPE html>
#     <html lang="en">
#     <head>
#         <meta charset="UTF-8">
#         <meta name="viewport" content="width=device-width, initial-scale=1.0">
#         <title>Jain and Kumar Pharmacy</title>
#         <style>
#             body {
#                 font-family: Arial, sans-serif;
#                 margin: 0;
#                 padding: 0;
#                 background-color: #f0f0f0;
#             }
#             .container {
#                 max-width: 800px;
#                 margin: 20px auto;
#                 padding: 20px;
#                 background-color: #fff;
#                 border-radius: 5px;
#                 box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
#             }
#             h1 {
#                 text-align: center;
#                 color: #333;
#             }
#             p {
#                 color: #666;
#                 line-height: 1.6;
#             }
#             .contact-info {
#                 margin-top: 20px;
#             }
#             .contact-info p {
#                 margin-bottom: 10px;
#             }
#             .contact-info p:last-child {
#                 margin-bottom: 0;
#             }
#             .contact-info strong {
#                 color: #333;
#             }
#             .order-button {
#                 display: block;
#                 width: 200px;
#                 margin: 20px auto;
#                 padding: 10px 20px;
#                 text-align: center;
#                 background-color: #007bff;
#                 color: #fff;
#                 border: none;
#                 border-radius: 5px;
#                 cursor: pointer;
#                 text-decoration: none;
#             }
#             .order-button:hover {
#                 background-color: #0056b3;
#             }
#         </style>
#     </head>
#     <body>
#         <div class="container">
#             <h1>Jain and Kumar Pharmacy</h1>
#             <p>You can order prescribed medicines from Jain Pharmacy by contacting us by calling us on the given contact numbers or email us</p>
#             <div class="contact-info">
#                 <p><strong>Phone Numbers:</strong></p>
#                 <p>Call us at: <a href="tel:9831122335">9831122335</a>, <a href="tel:9831122336">9831122336</a></p>
#                 <p><strong>Email:</strong></p>
#                 <p>Email us at: <a href="mailto:jainandkumarpharmacy@example.com">jainandkumarpharmacy@example.com</a></p>
#             </div>
#             <p></p>
#             <a class="order-button" href="#">Order Now</a>
#         </div>
#         <p style="text-align: center;">Thanks for choosing our company.
#     </body>
#     </html>
#     """
#     return html_content
# 
# # Generate HTML content
# html_code = generate_html()
# 
# # Display the HTML content
# from IPython.display import HTML
# HTML(html_code)
# 
# 
#